# Generated by Django 5.2.12 on 2026-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_inteligente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_platillo', models.CharField(max_length=100, verbose_name='Nombre Platillo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('categoria', models.CharField(choices=[('bebidas', 'Bebidas'), ('entrada', 'Entrada'), ('postre', 'Postre'), ('comida', 'Comida'), ('plato principal', 'Plato principal'), ('guarniciones', 'Guarniciones')], max_length=30, verbose_name='Categoria')),
                ('disponibilidad', models.BooleanField(default=False, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platillos', verbose_name='Imagen')),
            ],
        ),
    ]
