# Generated by Django 5.2.12 on 2026-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_inteligente', '0002_platillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
