# Generated by Django 5.2.12 on 2026-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina_inteligente', '0003_alter_platillo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='platillo',
            name='disponible',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
    ]
